### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


1.1

In [90]:
import numpy as np
import matplotlib.pyplot as plt

In [91]:
vector = np.random.rand(10)
print("Вектор (np.random.rand):", vector)
print("Розмір:", vector.shape)

Вектор (np.random.rand): [0.312378   0.31680959 0.30030838 0.82090364 0.31696381 0.63506311
 0.34790876 0.53918293 0.35493935 0.88446734]
Розмір: (10,)


In [92]:
vector_column = np.random.uniform(0, 1, (10, 1))
print("Вектор (np.random.uniform):", vector_column)
print("Розмір:", vector_column.shape)

Вектор (np.random.uniform): [[0.37552754]
 [0.2020599 ]
 [0.88554121]
 [0.36052624]
 [0.36125702]
 [0.00362138]
 [0.01679224]
 [0.08154141]
 [0.55417651]
 [0.35189087]]
Розмір: (10, 1)


1.2

In [93]:
# Створення матриці
matrix = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])

print("Матриця matrix:")
print(matrix)
print("Розмір:", matrix.shape)

Матриця matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


1.

In [94]:
updated_vector = np.round(vector + 10, 2)
print('Original:', vector)
print('Updated:', updated_vector)

Original: [0.312378   0.31680959 0.30030838 0.82090364 0.31696381 0.63506311
 0.34790876 0.53918293 0.35493935 0.88446734]
Updated: [10.31 10.32 10.3  10.82 10.32 10.64 10.35 10.54 10.35 10.88]


2.

In [95]:
updated_matrix = matrix*2
print('Original:\n', matrix)
print('Updated:\n', updated_matrix)

Original:
 [[11 14 17]
 [20 23 26]
 [29 32 35]]
Updated:
 [[22 28 34]
 [40 46 52]
 [58 64 70]]


3.

In [96]:
new_vector = vector**2
print('Original:', vector)
print('New:', new_vector)

Original: [0.312378   0.31680959 0.30030838 0.82090364 0.31696381 0.63506311
 0.34790876 0.53918293 0.35493935 0.88446734]
New: [0.09758002 0.10036832 0.09018512 0.67388279 0.10046606 0.40330516
 0.12104051 0.29071823 0.12598194 0.78228248]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [97]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

1.

In [98]:
result_matrix = np.dot(B,A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


2.

In [99]:
result = np.dot(result_matrix,C)
print(result)

[[0.5202]
 [0.2846]]


3.

In [100]:
result_D = np.dot(result_matrix,D)
print(result_D)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




1.

In [101]:
result_matrix_t = result_matrix.T
print("Транспонована матриця result_matrix", result_matrix_t, sep='\n')

Транспонована матриця result_matrix
[[0.7281 0.2034]
 [0.5202 0.2846]]


2.

In [102]:
vector_row = vector.reshape(1, 10)
vector_t = vector.T
print('Original vector:\n', vector_row)
print("Транспонований vector \n", vector_t)

Original vector:
 [[0.312378   0.31680959 0.30030838 0.82090364 0.31696381 0.63506311
  0.34790876 0.53918293 0.35493935 0.88446734]]
Транспонований vector 
 [0.312378   0.31680959 0.30030838 0.82090364 0.31696381 0.63506311
 0.34790876 0.53918293 0.35493935 0.88446734]


Так. Вектор був рядком, після транспонування має вигляд стовпця

3.

In [103]:
column_vector = np.expand_dims(vector, axis=1)

print("Оригінальний vector\n",vector.shape,"\n", vector)
print("Стовпчиковий vector\n", column_vector.shape,"\n", column_vector)

Оригінальний vector
 (10,) 
 [0.312378   0.31680959 0.30030838 0.82090364 0.31696381 0.63506311
 0.34790876 0.53918293 0.35493935 0.88446734]
Стовпчиковий vector
 (10, 1) 
 [[0.312378  ]
 [0.31680959]
 [0.30030838]
 [0.82090364]
 [0.31696381]
 [0.63506311]
 [0.34790876]
 [0.53918293]
 [0.35493935]
 [0.88446734]]


vector має (10,)-це одновимірний вектор.

column_vector має(10, 1)-це двовимірний вектор.

4.

In [104]:
column_vector_t = column_vector.T
print('Original:\n', column_vector.shape,"\n", column_vector)
print("Транспонований: \n", column_vector_t.shape,"\n", column_vector_t)

Original:
 (10, 1) 
 [[0.312378  ]
 [0.31680959]
 [0.30030838]
 [0.82090364]
 [0.31696381]
 [0.63506311]
 [0.34790876]
 [0.53918293]
 [0.35493935]
 [0.88446734]]
Транспонований: 
 (1, 10) 
 [[0.312378   0.31680959 0.30030838 0.82090364 0.31696381 0.63506311
  0.34790876 0.53918293 0.35493935 0.88446734]]
